version: "3.3"
networks:
  lnnet:

services:
  bitcoind:
    container_name: bitcoind
    build:
        context: bitcoind
    image: lnbook/bitcoind:latest
    networks:
      - lnnet
    expose:
      - "18443"
      - "12005"
      - "12006"
    restart: always

  Aa:
    container_name: Aa
    build:
      context: c-lightning
    image: lnbook/c-lightning:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always
    depends_on:
      - bitcoind

  Bb:
    container_name: Bb
    build:
      context: c-lightning
    image: lnbook/c-lightning:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always
    depends_on:
      - bitcoind

  Cc:
    container_name: Cc
    build:
      context: c-lightning
    image: lnbook/c-lightning:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always
    depends_on:
      - bitcoind

  Dd:
    container_name: Dd
    build:
      context: c-lightning
    image: lnbook/c-lightning:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always
    depends_on:
      - bitcoind

  Ee:
    container_name: Ee
    build:
      context: c-lightning
    image: lnbook/c-lightning:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always
    depends_on:
      - bitcoind

  Ff:
    container_name: Ff
    build:
      context: c-lightning
    image: lnbook/c-lightning:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always
    depends_on:
      - bitcoind
